### PR TITLE
Standard plotting tools

### PR DESCRIPTION
**Pull request by DriesAllaerts**
Adds plotting tools for time-height data (in pandas.dataFrame format) to plotting.py:
- plot_timeheight(): plot time-height contours
- plot_timehistory_at_height() and plot_timehistory_at_heights(): plot time history at given height(s)
- plot_profile() and plot_profile_evolution(): plot vertical profiles at given time(s)
- plot_spectrum(): plot frequency spectrum at given height and time(s)

A notebook demonstrating the various plotting tools is included as well

### CODE REVIEW

**Comment by ewquon** [comment]
Should we have a flag to turn on/off the subfigure labels (a), (b), ... etc?

**Comment by ewquon** [comment]
Should `plot_timeheight` vertically stack the subaxes instead of horizontally? Or more generally, an option to indicate the stacking direction?

**Comment by ewquon** [comment]
For `plot_profile_evolution`, can you add a colormap argument so that it's easier to see how the different curves are related in time?

**Comment by ewquon** [comment]
More generally, I'd like to have a `**kwargs` argument in each `plot_*` that is directly passed onto the actual matplotlib plot command to allow for additional fine tuning (and hacks).

**Comment by jsauer-NCAR** [comment]
Doing my best to keep up with all the great additions here...  

I noticed a few things like hard-coded paths to data directories in the helper-example notebook which makes that notebook... well... not helpful since those paths nor necessarily even the same data files are available to someone trying to use the notebook. 
The computation of spectra should probably be pulled outside of the plot_spectra routine.  

Finally, I'll hope it will be ok that when others in MMC do find the time to jump in and start working with all these great code additions, no offense is taken when changes/modifications are proposed.

All that to say it is nice to see the two of you pushing capability into the repos.  Hopefully others can get on board soon too.

**Comment by DriesAllaerts** [comment]
Thank you all for the feedback. I modified the plotting library to take your comments into account:
- flag to turn subfigure labels on/off: check
- stack plots vertically in plot_timeheight: check
- add colormap argument for multiple profiles in time: check

Some other modifications:
- merge plot_timehistory_at_height and plot_timehistory_at_heights into one function, adding an optional argument stack_by which can be set to "datasets" or "heights"
- similar merge of plot_profile and plot_profile_evolution with stack_by "datasets" or "times"

@jsauer-NCAR 
I'm working on getting an example dataset on the repository and will remove the hard-coded paths, good point Jeremy.

I'm not sure why you want the computation of the spectra to be pulled out of the plot_spectra routine as it just uses the scipy.signal.welch functionality. We can discuss this further if you prefer to compute spectra differently.

@ewquon 
I did not yet replace pivot with unstacking of MultiIndex DataFrames as this messed up the time axis in timeheight plots. Feel free to dive in and make that change. For now I assume the input is a pandas dataframe with a single index "datetime" and with a column "height". In the future we might want to make this more general, e.g., accept both single and multi index dataframes, make "height" column optional, allow multiple names for time index, ...

Finally, my view of the plotting library is that it should provide an example of how to plot data from one or multiple pandas DataFrames, and it should serve as a starting point for more detailed (and personal) plotting tools that aim for publication quality figures. That said, I definitely encourage people to propose changes or modification to the plotting library to make it more powerful, more general or more user-friendly. No offense will be taken :)

**Comment by jsauer-NCAR** [comment]
I've pulled your new notebook and other mods, and exercised all of the cells but strictly working from a processed TTU dataset for all of the plots.  That processed dataset comes directly out of the process_TTU_tower.ipynb that @ewquon polished up from my pending merge.  If you are open to the idea, the example notebook could just work with a TTU dataset which everyone can create on their own and in a consistent manner using the other tools that have been created?  

That way no one has to pull a dataset from one of your model runs to pick these up and just get their feet wet.

As for the computing of spectra, I think it would just be nice to have that separated because the function it exercises is called plot_spectra, not plot and compute spectra.  Being able to change filter and other aspects involved in the spectra just lends flexibility and keeps the plot_spectra doing only that job... plotting spectra.

**Comment by DriesAllaerts** [comment]
I adapted the example notebook to work with the processed TTU dataset from process_TTU_tower.ipynb.

For the spectra: I don't know how a separate function should look like and where it should live in the repository, so for now I just focused on example plotting tools and I added a todo note saying that we might want to separate the calculation and plotting of the spectra.

**Comment by jsauer-NCAR** [comment]
Notebook updates and other polishing steps look great Dries, thanks for accommodating the feedback. The TODO note for addition of a compute_spectra function down the road makes sense to me for now.  Anything else you are planning to do before merging this PR?

**Comment by ewquon** [comment]
This looks good to me.

**Comment by DriesAllaerts** [comment]
@jsauer-NCAR I don't plan to add anything else to this PR. There are some things I'd like to add or improve in the future but I need more time for that. I'll create a new PR whenever those changes are ready to be merged. I think the current form is polished enough and can be merged so that other people can start using it.

**Pull request merged**
