### PR TITLE
Draft MMC_Data class.

### PR DESCRIPTION
**Pull request by jsauer-NCAR**
@ewquon Is this what is meant by tagging a member in step 7 of slide 8 in GroovingGithub?

### CODE REVIEW

**Comment by ewquon** [comment]
> @ewquon Is this what is meant by tagging a member in step 7 of slide 8 in GroovingGithub?

Yes. Or you could formally assign a reviewer on the list on the right, but that doesn't change our workflow.

**Comment by jsauer-NCAR** [comment]
@ewquon Can we go ahead and merge this?

**Comment by ewquon** [comment]
See https://github.com/jsauer-NCAR/mmctools/pull/1

**Comment by ewquon** [comment]
See https://github.com/jsauer-NCAR/mmctools/pull/2

**Comment by ewquon** [comment]
@jsauer-NCAR If you don't have any more edits, then let's merge and close this :)

**Pull request merged**
