### PR TITLE
Fix bugs in wrf/utils.py

### PR DESCRIPTION
**Pull request by ewquon**
FYI @jsauer-NCAR

### CODE REVIEW

**Comment by jsauer-NCAR** [comment]
> FYI @jsauer-NCAR

My apologies on that @ewquon, I probably should have noticed the problems that would be caused for the other functions in the source file by adding a standard-ish xarray import. It definitely slipped by since I was only importing the function I added into notebooks as opposed to any of the other functions that already existed there, and to be honest I really had no use for anything that was already in there.  That is definitely something that a simple regression test for the original functionality would have caught.  Would be nice to add regression tests into the scope of work for this project.

**Comment by ewquon** [comment]
> Would be nice to add regression tests into the scope of work for this project.

😁

**Comment by ewquon** [comment]
Also, @jsauer-NCAR, the call out was just a heads up to let you know that I pushed this through in a hurry.

**Comment by jsauer-NCAR** [comment]
Much appreciated @ewquon. The apology was just that with some fluff.  More diligence would have been prudent on my part so it seemed right to apologize. I'll say this, I'm grateful the processes you've promoted for  us all to adopt in collaborative development across the project has resulted in a rapid recognition and fix of an issue (by you here and inevitably others later). That is a sign we're moving in the right direction. The easy example of why regression tests being called out in AOPs would be a good thing, just seemed like a cherry on top. ;-)

**Pull request merged**
