### PR TITLE
Allow spectras to be calculated for a list of variables

### PR DESCRIPTION
**Pull request by rthedin**
Allows the calculation of spectras for several variables at once.
Example:
```
calc_spectra(dataset,
             var_oi=['u', 'v' ,'w', 'wspd'],
             spectra_dim='datetime',
             level_dim='height',
             )
```

### CODE REVIEW

**Comment by rthedin** [comment]
@phawbeck It looks like I don't have permissions to request your review.

**Comment by phawbeck** [comment]
No worries - this works just as well. Just for tracking, did you test this out to make sure it still works when specifying 1 variable and also works when specifying a list?

**Comment by rthedin** [comment]
Yes. It also works with a single variable. If you see the changes I made, I simply changed the way you are dropping some variables from the dataset so that it can handle multiple variables. The `power_spectral_density` function already takes multiple variables so this is actually a very minor modification to the code.

**Comment by phawbeck** [comment]
Sounds good - thanks for adding this!

**Pull request merged**
