### PR TITLE
Add ERA5 class for interacting with Copernicus CDS

### PR DESCRIPTION
**Pull request by ewquon**
Example usage:
```
import pandas as pd
from mmctools.wrf.preprocessing import ERA5

datetimes = pd.date_range(start='2019-12-25 12:00',
                          end='2019-12-27 00:00',
                          freq='1h')

icbc = ERA5()
icbc.download(datetimes)
```

### CODE REVIEW

**Comment by ewquon** [comment]
I'm going to pull this in for @wlassman - we can create another PR to fix any issues or add features if needed, but I've been using this code without issue.

**Comment by phawbeck** [comment]
Sorry - somehow this slipped through the cracks. I'll pull it and test it out.

**Comment by phawbeck** [comment]
This worked, the only thing I'd request is to be able to download the data to a different directory. Or do you see this as something that you install in bin/ and then run from anywhere?

**Comment by ewquon** [comment]
No worries. I always feel like I’m missing something from github, but I feel like if they send even one more notification it’d be “GAH TOO MANY EMAILS”

**Comment by ewquon** [comment]
My expectation is that users figure out how to incorporate this into their workflow on their own: put it in a python script to run from the shell, run it in a notebook, or use it inside of a larger preprocessing framework. Adding a `path` parameter would be very useful, though. I'm on it.

**Comment by ewquon** [comment]
@phawbeck, added this capability in #95 -- let me know if it works as you'd expect.

**Pull request merged**
