### PR TITLE
WRF-specific python dictionary

### PR DESCRIPTION
**Pull request by phawbeck**

### CODE REVIEW

**Comment by ewquon** [comment]
I see that you renamed the function calls in WriteWRFData2NCDF, but does wrf/utils.py still have the old function names? And the functions still do not appear to have docstrings. Perhaps you haven't pushed all your commits?

**Comment by ewquon** [comment]
Sorry to pile on. Could you also remove the .pyc file? I've added a .gitignore file that will automatically ignore these files in the future.

**Comment by ewquon** [comment]
So what did we decide was the convention for "staggered" vs "unstaggered"?

**Comment by phawbeck** [comment]
Staggered = unstaggered + 1
i.e., u is staggered in x meaning shape(u) = (nz,ny,nx+1)

**Comment by ewquon** [comment]
OK, sounds good!

**Pull request merged**
