### PR TITLE
Adding calc_spectra function and preprocessing change

### PR DESCRIPTION
**Pull request by phawbeck**
The calc_spectra function is intended to replace the model4D_*spectra functions. Near-term goal is to add co-spectra capability to it.

The netCDF times function simply grabs time values from netCDF files so that pre-processing can have an overwrite-sst functionality.

### CODE REVIEW

**Comment by rthedin** [comment]
Pat, can we add `tstart` and `interval` to the call of `calc_spectra`, which is then passed on to `power_spectral_density`? I'm not sure if you left that out for any specific reason. I added back so I could do spectras in chunks of data, given a long time-series.

```
def calc_spectra(data,
                 # ...
                 tstart=None,
                 interval=None
                 ):
```
and then add the same parameters to the call of `power_spectral_density`:
```
 psd = power_spectral_density(spec_dat_df,
                              window_type=window,
                              detrend=detrend,
                              num_overlap=num_overlap,
                              tstart=tstart,
                              interval=interval)
```

**Comment by phawbeck** [comment]
Good call, just added - try it out for me!

Just a note for future reference, I think it might be worthwhile to update the power_spectral_density function to be used with spatial data. Currently there are a lot of assumptions of datetime values that don't allow everything to work for spatial data.

**Review by ewquon — APPROVED** [review]
This looks great! Thanks for clean code and clear documentation.

**Comment by phawbeck** [comment]
@rthedin Once we confirm that the code works using interval + tstart, I'll pull this in.

**Comment by rthedin** [comment]
I know this has been merged/closed, but just for the sake of documentation, I've been testing this function for several days now and it's been working as expected.

**Pull request merged**
