### PR TITLE
Feature/sowfa input class

### PR DESCRIPTION
**Pull request by DriesAllaerts**
Clean up `coupling.internal.*_to_sowfa` functions to write data to SOWFA input files by generating a class. This PR addresses issue #28 raised by @ewquon . The old `wrf_to_sowfa` notebook is removed as new and up-to-date notebooks using the `coupling.internal.SowfaInput` class are added in a2e-mmc/assessment#12

### CODE REVIEW

**Comment by ewquon** [comment]
@DriesAllaerts would it make sense to change the `mmctools.coupling.internal` module to `mmctools.coupling.sowfa`? I can probably piggyback off of your `write_BCs` and `write_ICs` functions for my boundary coupling.

**Comment by DriesAllaerts** [comment]
@ewquon if you think this would be a better structure and you can piggyback off of the existing functions then go ahead. I'm fine either way

**Comment by ewquon** [comment]
How's this look? 

Also, could you update `assessment/studies/coupling_comparison/preprocessing/internal/*.ipynb`?

**Comment by DriesAllaerts** [comment]
@ewquon I will update the notebooks in question in separate PR in the a2e/assessment repository

**Pull request merged**
