### PR TITLE
Add conda environment file

### PR DESCRIPTION
**Pull request by ewquon**
Usage:

```
conda create -n mmc  # to create a new environment (optional)  
conda activate mmc  # or conda activate my_existing_env
conda env update --file environment.yaml
```

### CODE REVIEW

**Comment by ewquon** [comment]
@phawbeck can you see if `conda env update --file environment.yaml` breaks your environment for any reason?

**Comment by phawbeck** [comment]
2 things went wrong when doing this but once they were addressed this worked, but maybe not how I was expecting:
1. I ran it in a directory other than where my environment.yml file was and an error occurred saying it couldn't find that file.
2. I went to my home dir where the file exists but it was ".yml" and not the expected ".yaml" so the same error occurred. I moved the file to be ".yaml" and everything ran as expected.

Once this ran, all of the versions were created on my 'base' environment and not the environment that I had sourced. Maybe this was an issue on my end but I don't know how to test my notebooks since Jupyter is only seeing my environment (different from 'base').

**Comment by phawbeck** [comment]
I just found that you've provided an environment.yaml file - am I supposed to download that and replace my existing one? It seems like there should be a "name: mmc" at the top (and possible a "prefix: /path/to/conda/environment" at the bottom).

**Comment by ewquon** [comment]
The enivornment.yaml file I added should come with mmctools, and you shouldn't be overwriting anything with it. The idea is to call `conda env update` with this file in order to download the specific versions of all the dependencies (e.g., xarrays) if you don't have them already. This should work for new and existing environments. It should perform the updates within your current environment.

**Comment by phawbeck** [comment]
After creating a new environment, updating to the mmc yaml file, installing 'ipykernel', and **linking to the correct python executable into my kernel path** I was able to get this working without any issues in the notebook I am currently working with.

**Pull request merged**
