### PR TITLE
Improved control over axes grid

### PR DESCRIPTION
**Pull request by DriesAllaerts**
Some additional option to improve control over axes grid:
- Option to specify number of columns
- Option to specify size of subfigures
- Option in `plot_profile` to define index ordering of fields, i.e., having fields vary fastest or slowest (relative to datasets/times) when filling in the axes grid row by row.

### CODE REVIEW

**Comment by ewquon** [comment]
@DriesAllaerts  Can you update the example notebook to demonstrate the flipping of rows/columns?

**Comment by DriesAllaerts** [comment]
Something like this? Or would you prefer two examples showing the difference?

**Comment by ewquon** [comment]
I think this is good enough, the only difference would the be `fieldorder='F'` kwarg, right?

**Comment by DriesAllaerts** [comment]
That is correct. The number of rows and columns would be adjusted automatically. If you have a certain preference on the number of column, you could specify that using the `ncols` argument

**Pull request merged**
