### PR TITLE
Add installer

### PR DESCRIPTION
**Pull request by ewquon**
To install, run `pip install -e mmctools` after cloning the repository.

### CODE REVIEW

**Comment by ewquon** [comment]
@phawbeck ready?

https://youtu.be/ReJ3RltihME?t=309

**Comment by phawbeck** [comment]
Wanted to test it out before merging. I did the following:
1. Clone ewquon/mmctools/feature/add_setup 
2. 'cd' into mmctools
3. run 'pip install -e mmctools'
From (3) I got the following error: "ERROR: mmctools is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+)."

I tried moving up a directory and ran again (didn't think this would work, but worth a shot):
"ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Users/hawbecke/Code/test_env/mmctools"

Is there a step missing? I'm running this on my Mac.

**Comment by ewquon** [comment]
The command is actually `pip install -e /path/to/dir/containing/setup_py`... and I'm guessing you ran pip install from inside the mmctools directory. So in that case you would do `pip install -e .`

**Comment by phawbeck** [comment]
I realized that when I cloned the repo, it defaults to 'master' branch... checked out this feature branch and installed. Ended w/ 
"Successfully installed dask-2.20.0 mmctools netcdf4-1.5.3 numpy-1.18.1 pandas-1.0.1 pyyaml-5.3.1 scipy-1.4.1 xarray-0.15.0"

**Comment by phawbeck** [comment]
One thing that might be helpful to add with this (especially since a lot of people will only be installing this for use in the jupyter notebooks) is to create the kernel.json file that's needed for jupyter notebooks to "see" the new environment?

**Comment by ewquon** [comment]
So the `-e` option makes the installation "editable". So instead of permanently installing the code in its current state, it creates a link to wherever the mmctools folder is. So you can `git checkout` branches after installing and also do code development after installing without having to re-install. I guess the problem right now is that setup.py isn't in the master branch yet...

**Comment by phawbeck** [comment]
Ahh ok - that's nice! After I installed, I wasn't able to find the new kernel in my jupyter notebook, though - how do I get it so that it can be an option under "kernels"?

**Comment by ewquon** [comment]
You're not installing a new kernel, you're installing a new package. `pip install` is an alternative to `conda install -c conda-forge`. Is the `pip install -e` installed package visible from your python environment on the HPC machines you're using? I tested it with my setup--removed my old a2e-mmc path from the `$PYTHONPATH` environment variable, so that there's no way for python to know about the code without it having been installed--and then tried using mmctools and it worked for me.

**Comment by phawbeck** [comment]
Ahh ok - sorry. I understand now. The trick I learned for this is installing pip through conda, then calling that version of pip (somewhere in /local/envs/... or something like that) to install something. That will install it within that conda env. This worked for me!

**Pull request merged**
